### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by mitogh**
Template field should return the template of the file, since makes confuse to have a templates file that returns the post type. 

And added the post type as a separate field.

### CODE REVIEW

**Comment by adamf321** [comment]
Hey @mitogh I disagree with this change. the reason is that the API should not expose the workings of WordPress. It should output something which is useful for a front-end app. To me it's right for that to be the page template if there is one, otherwise the post_type. We need to think in terms of the consumer of this data (our angular app).

I guess we could change the name of the field to data_type or something like that (instead of template). And then use 'page_template' for page's with templates. This way we're not making assumptions about how the front-end will use this data (it might not just be to decide which template to use).

One other thing I was thinking about is the name of the extension and endpoint ("view"). My original idea is that it would take any url and convert it into a view. This means it would also work for archive pages, etc.

The advantage is that the front-end doesn't have to know what type of view it is asking for. However, the disadvantage is that this API becomes a lot more complex, and its use becomes very wide (would it still be useful for a mobile app for example?).

The alternative is to change the name of the package/endpoint to "post" and create a new one for archive pages, search results, etc. The only issue here is that the front-end needs to know which to call. We'd need to add a way of configuring archive page routes for example.

What do you think?

**Comment by mitogh** [comment]
Thanks for the feedback.

What part exactly of you are not agree, the post type? 

Since I just added as a fallback because you were using that on the template field, and as the field is called template I think should return the template, right?

Yes I don't see any value in having the post type but just added in order to keep it in there since you were adding the value on a field where does not have too much relationship.

Let me know to update as required.

Yes I agree we can keep a module for that. I'm working on other changes as well will push ASAP but are not related with this. 

Let me know to proceed in consequence.

**Comment by adamf321** [comment]
Yes, the post_type and templates changes. I think we could do something in between yours and mine, eg:

``` php
$type = $post->post_type;
if ( 'page' === $post->post_type ) {
  $template_slug = get_page_template_slug( $post->ID );
  if ( ! empty( $template_slug ) {
    $type .= '_' . basename( $template_slug, '.php' );
  }
}
return $type
```

And then return the just one field, "type" in the json. How about this?

Ok, i'll change the package/repo name to wp-endpoints-post for now. We can look at archive pages when we need them (i think for shootx).

What are the other changes?

**Comment by mitogh** [comment]
What’s the difference between this and the current changes?

Besides rename template in type, for me type is that define the type of a post, and template the template used on that page.

Basically structural changes nothing major :).

**Comment by adamf321** [comment]
Yes, that's it. So the REST api just returns one field, "type". And we drop the template field altogether.

**Comment by mitogh** [comment]
I think both are two different things a field that repesents the type shouldn't have a template as his value. It either case should be the type of the post or just page. I don't see the reason to have the template as the value for type

**Comment by adamf321** [comment]
Because they're all the same to the front-end. You're thinking in terms of WP.
A cpt of type "product" is just a type of object to the front-end
The same as a page with template "services" - again services is just a type of object. We just happen to implement it in wp using page templates. It could just as easily be a cpt.

So for the front-end we should just have a "type" which would be "product" or "services".

**Comment by mitogh** [comment]
Ok I get your point now. It makes more sense in this way, just one last thing what happened with page templates with this name: 

store-locations

The type should be: 

Store Locations
store locations
store-locations

At the moment the API is suing the third option.

**Comment by adamf321** [comment]
I think that's fine. We can then give the angular template the same name: templates/store-locations/template.html

**Comment by mitogh** [comment]
Cool will update then.

Thanks

**Comment by mitogh** [comment]
I did the updates as you suggested, I think we should rename the class but I'm doing that on a different branch.

**Comment by adamf321** [comment]
Looks good.

I'm going to update the repo / package name now

**Pull request merged**
